inc:
  # Blog Information
  title:        "Sarath Lakshman"
  subtitle:     "Thoughts of an engineer on computer systems"
  #logo:         logo.png
  
  # Company information
  cover_image:  home-cover.jpg
  company:      Sarath Lakshman
  url:          http://www.sarathlakshman.com/
  facebook:     sarathlakshman
  twitter:      t3rm1n4l
  about_link:   http://sarathlakshman.com/about/
  
  # Header
  tagline:      ""
  
  # Comments
  disqus:
    # Eg. "exampleblog" Set to false to disable comments
    shortname:  "slynux"
  
  # Sharing settings
  sharing:
    twitter:    true
    facebook:   true
    gplus:      true
    hn:         true
    
  
 # Analytics     
  analytics:
    google: true # Add tracking code in _includes/_google-analytics.html
      
      
  # Google Fonts
  # eg. 'Droid+Sans:400,700|Droid+Serif:400,700'
  google_font: 'Droid+Sans|Oxygen'
  
  # Setup your fonts, colors etc at _assets/stylesheets/main.scss

url:         http://www.sarathlakshman.com
source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
include:     ['.htaccess']
exclude:     []
timezone:    nil

# Show future posts
future:      false
show_drafts: nil
limit_posts: 0
highlighter:    true

relative_permalinks: true

permalink:     /:year/:month/:day/:title.html
paginate_path: 'page:num'
paginate: 5

markdown:      kramdown
markdown_ext:  markdown,mkd,mkdn,md
textile_ext:   textile

excerpt_separator: "<!-- more -->"

safe:        false
host:        0.0.0.0
port:        4000
baseurl:     /
lsi:         false

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: false

  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style

redcloth:
  hard_breaks: true

sass:
  style: :compressed
  sass_dir: _sass
